---
driver:
  name: dokken
  privileged: true
  chef_version: <%= ENV['CHEF_VERSION'] || 'current' %>

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver:
      image: dokken/centos-7
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN /usr/bin/yum -y update

suites:
  - name: test
    run_list:
    verifier:
      inspec_tests:
        - test/integration/default
